---
apiVersion: v1
kind: ConfigMap
metadata:
  name: personserviceconfig
  namespace: {{ .Values.namespace }}
data:
  DATABASE_DRIVER: "org.postgresql.Driver"
  HIBERNATE_DIALOG: "org.hibernate.dialect.PostgreSQL95Dialect"
  JPA_DDL_AUTO: "update"
  JPA_GENERETE_DDL: "true"
  SHOW_SQL: "true"
  AUTH_URL: "http://auth-service:80"
---
apiVersion: v1
kind: Secret
metadata:
  name: personservicesecret
  namespace: {{ .Values.namespace }}
type:
  Opaque
data:
  DATABASE_URI: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.externalPostgresql.postgresqlHost .Values.externalPostgresql.postgresqlPort .Values.externalPostgresql.postgresqlDatabase | b64enc | quote }}
  DATABASE_LOGIN: {{ printf "%s" .Values.externalPostgresql.postgresqlUserName | b64enc | quote }}
  DATABASE_PASSWORD: {{ printf "%s" .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigatewayconfig
  namespace: {{ .Values.namespace }}
data:
  AUTH_SERVICE_URL: http://auth-service:80
  PERSON_SERVICE_URL: http://person-service:80