apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-gateway-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /health
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigatewayservice
                port:
                  number: {{ .Values.service.apigateway.port }}          
