
apiVersion: v1
kind: Service
metadata:
  name: apigatewayservice
  namespace: {{ .Values.namespace }}
  labels:
    app: apigatewayservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apigateway.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: apigatewayservice
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  namespace: {{ .Values.namespace }}
  labels:
    app: person-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.personservice.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: person-service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
  labels:
    app: auth-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.authservice.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: auth-service

