# Default values for first-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: gateway



images:
    authservice:
        repository: eugene89/auth-service
        replicaCount: 1
    personservice:
        repository: eugene89/person-service
        replicaCount: 1
    apigateway:
        repository: eugene89/api-gateway-service
        replicaCount: 1
ingress:
  hostname: arch.homework

service:
  type: NodePort
  authservice:
    port: 80
  personservice:
    port: 80
  apigateway:
    port: 8080

externalPostgresql:
  postgresqlUserName: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: "postgres"
  postgresqlPort: "5432"

postgres:
  image: postgres:11
